"""Merge every labs/*/05_CONFIG/requirements.txt into one VM image requirement set.

Writes  vm-provisioning/requirements.txt  (the union, de-duplicated, with a note
of which labs asked for each package). The VM vendor installs that one file.

Usage:  python tools/aggregate_requirements.py [--check]
    --check : exit 1 if vm-provisioning/requirements.txt is stale (for CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

KIT = Path(__file__).resolve().parent.parent
OUT = KIT / "vm-provisioning" / "requirements.txt"

REQ_LINE = re.compile(r"^\s*([A-Za-z0-9._-]+)\s*(.*)$")


def collect() -> str:
    specs: dict[str, set[str]] = defaultdict(set)
    wanted_by: dict[str, set[str]] = defaultdict(set)

    for req in sorted((KIT / "labs").glob("*/05_CONFIG/requirements.txt")):
        lab = req.parents[1].name
        for raw in req.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            m = REQ_LINE.match(line)
            if not m:
                continue
            name = m.group(1).lower()
            specs[name].add(line)
            wanted_by[name].add(lab)

    body = [
        "# AUTO-GENERATED by tools/aggregate_requirements.py - do not edit by hand.",
        "# Union of every labs/*/05_CONFIG/requirements.txt. Install this on the VM image.",
        "",
    ]
    for name in sorted(specs):
        variants = sorted(specs[name])
        chosen = variants[0]
        labs = ", ".join(sorted(wanted_by[name]))
        if len(variants) > 1:
            body.append(f"# NOTE: conflicting specs for {name}: {variants} - picked '{chosen}'")
        body.append(f"{chosen}    # {labs}")
    return "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    new = collect()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    if args.check:
        if new != old:
            print(f"{OUT.relative_to(KIT)} is stale - run tools/aggregate_requirements.py")
            return 1
        print("vm-provisioning/requirements.txt is up to date.")
        return 0

    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.relative_to(KIT)}")
    print(new)
    return 0


if __name__ == "__main__":
    sys.exit(main())
